# Generated by Django 4.2.7 on 2023-11-11 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_short',
        ),
    ]
